spring.application.name=backend
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/inventory_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
jwt.secret=${JWT_SECRET:94f6c46cb32145b0a7019f3900350d32b845187740e5dcbd41369d71c897f262}
jwt.expiration=86400000

server.port=${SERVER_PORT:8080}

